version: '3.8'

services:
  app:
    build:
     context: .
    container_name: reservesapi
    restart: unless-stopped
    ports:
      - "443:443"  # HTTPS
    environment:
      - PORT=443
    networks:
      - internal
networks:
  internal:
    name: xarxa_docker1
    external: true

